import 'package:flutter/material.dart';
import 'cloud_models.dart';
import 'farsha_repository.dart';
import 'ui_v2_components.dart';
class MaterialsPage extends StatefulWidget{const MaterialsPage({super.key,required this.membership,required this.repository});final InstitutionMembership membership;final FarshaRepository repository;@override State<MaterialsPage> createState()=>_MaterialsPageState();}
class _MaterialsPageState extends State<MaterialsPage>{
 late Future<List<AddonTypeRecord>> materials=load();Future<List<AddonTypeRecord>> load()async=>(await widget.repository.loadAddonTypes(widget.membership.institutionId)).where((x)=>x.trackStock).toList();void reload()=>setState(()=>materials=load());
 Future<void> receive(AddonTypeRecord a)async{final q=TextEditingController(),cost=TextEditingController(text:a.defaultCostPrice.toStringAsFixed(2)),note=TextEditingController();final ok=await dialog('توريد '+a.name,[TextField(controller:q,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'الكمية ('+a.unit+')')),TextField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'التكلفة / الوحدة')),TextField(controller:note,decoration:const InputDecoration(labelText:'ملاحظات'))]);final qty=double.tryParse(q.text)??0,co=double.tryParse(cost.text)??0,n=note.text;for(final c in[q,cost,note])c.dispose();if(ok&&qty>0){await widget.repository.receiveAddonStock(widget.membership.institutionId,a.id,qty,co,n);reload();}}
 Future<void> issue(AddonTypeRecord a)async{final sellers=await widget.repository.loadSellers(widget.membership.institutionId);if(sellers.isEmpty)return;String seller=sellers.first.id;final q=TextEditingController(),note=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(title:Text('تسليم '+a.name+' لبائع'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:seller,decoration:const InputDecoration(labelText:'البائع'),items:sellers.map((x)=>DropdownMenuItem(value:x.id,child:Text(x.name))).toList(),onChanged:(v)=>setD(()=>seller=v!)),TextField(controller:q,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'الكمية ('+a.unit+')')),TextField(controller:note,decoration:const InputDecoration(labelText:'ملاحظات / العملية'))]),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('تسليم'))])))??false;final qty=double.tryParse(q.text)??0,n=note.text;q.dispose();note.dispose();if(ok&&qty>0){await widget.repository.issueInternalAddon(widget.membership.institutionId,a.id,seller,qty,n);reload();}}
 Future<bool> dialog(String title,List<Widget> fields)async=>await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text(title),content:Column(mainAxisSize:MainAxisSize.min,children:fields.map((x)=>Padding(padding:const EdgeInsets.only(bottom:8),child:x)).toList()),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حفظ'))]))??false;
 @override Widget build(BuildContext context)=>FutureBuilder<List<AddonTypeRecord>>(future:materials,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());final rows=s.data!;String category(AddonTypeRecord a){final n=a.name.toLowerCase();if(n.contains('لباد')||n.contains('felt'))return 'لباد';if(n.contains('غراء')||n.contains('glue'))return 'غراء';if(n.contains('حديد')||n.contains('شريح')||n.contains('strip'))return 'حديد وشرائح';return 'مستلزمات أخرى';}final groups=<String,List<AddonTypeRecord>>{};for(final a in rows)groups.putIfAbsent(category(a),()=>[]).add(a);return ListView(padding:const EdgeInsets.all(16),children:[const Text('المستلزمات',style:TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text('المخزون والاستهلاك الداخلي منظم حسب النوع.',style:TextStyle(color:Colors.grey.shade700)),const SizedBox(height:16),if(rows.isEmpty)const EmptyState(title:'لا توجد مستلزمات مضافة',subtitle:'أضف لباد أو غراء أو حديد من إعدادات المخزون.',icon:Icons.handyman_outlined)else...groups.entries.expand((g)=>[SectionTitle(g.key),...g.value.map((a)=>Padding(padding:const EdgeInsets.only(bottom:8),child:Card(child:ListTile(leading:Container(width:40,height:40,decoration:BoxDecoration(color:(a.isLow?warningOrange:positiveGreen).withValues(alpha:.1),borderRadius:BorderRadius.circular(12)),child:Icon(a.isLow?Icons.warning_amber:Icons.handyman_outlined,color:a.isLow?warningOrange:positiveGreen)),title:Text(a.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text((a.behavior=='internal_consumable'?'استخدام داخلي':'للعميل')+' • '+a.stockQuantity.toStringAsFixed(2)+' '+a.unit+(a.isLow?' • مخزون منخفض':'')),trailing:PopupMenuButton<String>(onSelected:(v)=>v=='receive'?receive(a):issue(a),itemBuilder:(_)=>[const PopupMenuItem(value:'receive',child:Text('توريد مخزون')),if(a.behavior=='internal_consumable')const PopupMenuItem(value:'issue',child:Text('تسليم لبائع'))])))))]))]);});
}
