import 'package:flutter/material.dart';
import 'cloud_models.dart';
import 'farsha_repository.dart';
class MaterialsPage extends StatefulWidget{const MaterialsPage({super.key,required this.membership,required this.repository});final InstitutionMembership membership;final FarshaRepository repository;@override State<MaterialsPage> createState()=>_MaterialsPageState();}
class _MaterialsPageState extends State<MaterialsPage>{
 late Future<List<AddonTypeRecord>> materials=load();Future<List<AddonTypeRecord>> load()async=>(await widget.repository.loadAddonTypes(widget.membership.institutionId)).where((x)=>x.trackStock).toList();void reload()=>setState(()=>materials=load());
 Future<void> receive(AddonTypeRecord a)async{final q=TextEditingController(),cost=TextEditingController(text:a.defaultCostPrice.toStringAsFixed(2)),note=TextEditingController();final ok=await dialog('توريد '+a.name,[TextField(controller:q,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'الكمية ('+a.unit+')')),TextField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'التكلفة / الوحدة')),TextField(controller:note,decoration:const InputDecoration(labelText:'ملاحظات'))]);final qty=double.tryParse(q.text)??0,co=double.tryParse(cost.text)??0,n=note.text;for(final c in[q,cost,note])c.dispose();if(ok&&qty>0){await widget.repository.receiveAddonStock(widget.membership.institutionId,a.id,qty,co,n);reload();}}
 Future<void> issue(AddonTypeRecord a)async{final sellers=await widget.repository.loadSellers(widget.membership.institutionId);if(sellers.isEmpty)return;String seller=sellers.first.id;final q=TextEditingController(),note=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(d)=>StatefulBuilder(builder:(d,setD)=>AlertDialog(title:Text('تسليم '+a.name+' لبائع'),content:Column(mainAxisSize:MainAxisSize.min,children:[DropdownButtonFormField<String>(initialValue:seller,decoration:const InputDecoration(labelText:'البائع'),items:sellers.map((x)=>DropdownMenuItem(value:x.id,child:Text(x.name))).toList(),onChanged:(v)=>setD(()=>seller=v!)),TextField(controller:q,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'الكمية ('+a.unit+')')),TextField(controller:note,decoration:const InputDecoration(labelText:'ملاحظات / العملية'))]),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('تسليم'))])))??false;final qty=double.tryParse(q.text)??0,n=note.text;q.dispose();note.dispose();if(ok&&qty>0){await widget.repository.issueInternalAddon(widget.membership.institutionId,a.id,seller,qty,n);reload();}}
 Future<bool> dialog(String title,List<Widget> fields)async=>await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text(title),content:Column(mainAxisSize:MainAxisSize.min,children:fields.map((x)=>Padding(padding:const EdgeInsets.only(bottom:8),child:x)).toList()),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('إلغاء')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('حفظ'))]))??false;
 @override Widget build(BuildContext context)=>FutureBuilder<List<AddonTypeRecord>>(future:materials,builder:(c,s){if(!s.hasData)return const Center(child:CircularProgressIndicator());return ListView(padding:const EdgeInsets.all(16),children:[const Text('المستلزمات',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const Text('الغراء واللباد والشرائح وغيرها — المخزون الداخلي منفصل عن فاتورة العميل.'),const SizedBox(height:12),...s.data!.map((a)=>Card(color:a.isLow?Colors.orange.shade50:null,child:ListTile(leading:Icon(a.isLow?Icons.warning_amber:Icons.handyman_outlined),title:Text(a.name),subtitle:Text((a.behavior=='internal_consumable'?'داخلي':'للعميل')+' • '+a.stockQuantity.toStringAsFixed(2)+' '+a.unit+(a.isLow?' • مخزون منخفض':'')),trailing:PopupMenuButton<String>(onSelected:(v)=>v=='receive'?receive(a):issue(a),itemBuilder:(_)=>[const PopupMenuItem(value:'receive',child:Text('توريد مخزون')),if(a.behavior=='internal_consumable')const PopupMenuItem(value:'issue',child:Text('تسليم لبائع'))]))))]);});
}
