-- Make current write paths branch-aware while keeping backward-compatible signatures where possible.
create or replace function public.create_inventory_item(p_institution_id uuid,p_supplier_id uuid,p_name text,p_color text,p_length numeric,p_supplier_price numeric,p_wholesale_price numeric,p_low_stock_at numeric default 10,p_branch_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$declare result_id uuid;bid uuid;begin
 bid:=coalesce(p_branch_id,(select id from public.branches where institution_id=p_institution_id and is_default));
 if not public.can_manage_branch(bid,'inventory') then raise exception 'Insufficient branch permission';end if;
 if p_wholesale_price<p_supplier_price then raise exception 'Wholesale price cannot be below supplier price';end if;
 insert into public.inventory_items(institution_id,branch_id,name,color,remaining_length,wholesale_price,low_stock_at) values(p_institution_id,bid,trim(p_name),trim(p_color),p_length,p_wholesale_price,p_low_stock_at) returning id into result_id;
 insert into public.inventory_costs(inventory_id,institution_id,supplier_id,supplier_price) values(result_id,p_institution_id,p_supplier_id,p_supplier_price);
 insert into public.inventory_movements(institution_id,branch_id,inventory_id,movement_type,length_delta,source_type,source_id,note,created_by) values(p_institution_id,bid,result_id,'opening',p_length,'inventory',result_id,'Opening stock',auth.uid());
 return result_id;end$$;
revoke all on function public.create_inventory_item(uuid,uuid,text,text,numeric,numeric,numeric,numeric,uuid) from public,anon;grant execute on function public.create_inventory_item(uuid,uuid,text,text,numeric,numeric,numeric,numeric,uuid) to authenticated;

create or replace function public.record_supplier_delivery(p_institution_id uuid,p_supplier_id uuid,p_inventory_id uuid,p_length numeric,p_unit_cost numeric,p_wholesale_price numeric,p_reference text default '',p_notes text default '')
returns uuid language plpgsql security definer set search_path=public as $$declare inv public.inventory_items%rowtype;delivery_id uuid;line_total numeric;begin
 select * into inv from public.inventory_items where id=p_inventory_id and institution_id=p_institution_id for update;if not found then raise exception 'Inventory item not found';end if;
 if not public.can_manage_branch(inv.branch_id,'inventory') then raise exception 'Insufficient branch permission';end if;if p_length<=0 or p_unit_cost<0 then raise exception 'Invalid delivery values';end if;
 line_total:=round(p_length*inv.width*p_unit_cost,2);
 insert into public.supplier_deliveries(institution_id,branch_id,supplier_id,reference,notes,created_by) values(p_institution_id,inv.branch_id,p_supplier_id,coalesce(p_reference,''),coalesce(p_notes,''),auth.uid()) returning id into delivery_id;
 insert into public.supplier_delivery_items(institution_id,delivery_id,inventory_id,name_snapshot,color_snapshot,length,width,unit_cost,wholesale_price) values(p_institution_id,delivery_id,inv.id,inv.name,inv.color,p_length,inv.width,p_unit_cost,p_wholesale_price);
 update public.inventory_items set remaining_length=remaining_length+p_length,wholesale_price=p_wholesale_price where id=inv.id;update public.inventory_costs set supplier_id=p_supplier_id,supplier_price=p_unit_cost,updated_at=now() where inventory_id=inv.id;
 update public.suppliers set purchases_total=purchases_total+line_total where id=p_supplier_id and institution_id=p_institution_id;
 insert into public.supplier_account_entries(institution_id,branch_id,supplier_id,entry_type,balance_effect,reference,note,source_type,source_id,created_by) values(p_institution_id,inv.branch_id,p_supplier_id,'delivery',line_total,p_reference,p_notes,'delivery',delivery_id,auth.uid());
 insert into public.inventory_movements(institution_id,branch_id,inventory_id,movement_type,length_delta,source_type,source_id,note,created_by) values(p_institution_id,inv.branch_id,inv.id,'supplier_delivery',p_length,'supplier_delivery',delivery_id,p_notes,auth.uid());return delivery_id;end$$;
revoke all on function public.record_supplier_delivery(uuid,uuid,uuid,numeric,numeric,numeric,text,text) from public,anon;grant execute on function public.record_supplier_delivery(uuid,uuid,uuid,numeric,numeric,numeric,text,text) to authenticated;

create or replace function public.record_sale_v2(p_institution_id uuid,p_inventory_id uuid,p_seller_id uuid,p_driver_id uuid,p_customer_name text,p_length numeric,p_sale_price numeric,p_driver_fee numeric,p_notes text,p_payments jsonb,p_addons jsonb default '[]'::jsonb)
returns uuid language plpgsql security definer set search_path=public as $$
declare item public.inventory_items%rowtype;cost_row public.inventory_costs%rowtype;inst public.institutions%rowtype;seller public.institution_memberships%rowtype;result_id uuid;payment jsonb;addon jsonb;v_area numeric;v_carpet_total numeric;v_addon_sales numeric:=0;v_total numeric;v_paid numeric:=0;v_fee numeric:=0;v_method text;v_amount numeric;v_rate numeric;v_reference text;v_seller_profit numeric;v_commission numeric;v_primary_method text:='other';v_name text;v_unit text;v_qty numeric;v_sale_unit numeric;v_cost_unit numeric;v_addon_id uuid;v_supplier_id uuid;a public.addon_types%rowtype;
begin if auth.uid() is null then raise exception 'Authentication required';end if;select * into item from public.inventory_items where id=p_inventory_id and institution_id=p_institution_id for update;if not found or item.remaining_length<p_length then raise exception 'Requested length is unavailable';end if;
 if not public.can_manage_branch(item.branch_id,'sell') then raise exception 'Insufficient branch permission';end if;if auth.uid()<>p_seller_id and not public.has_institution_role(p_institution_id,array['owner']::public.institution_role[]) then raise exception 'Seller mismatch';end if;
 select * into cost_row from public.inventory_costs where inventory_id=item.id;if not found then raise exception 'Inventory cost is missing';end if;select * into seller from public.institution_memberships where institution_id=p_institution_id and user_id=p_seller_id and role='seller' and status='active';if not found and auth.uid()<>p_seller_id then raise exception 'Seller is not active';end if;
 if p_driver_id is not null and not exists(select 1 from public.institution_driver_connections where institution_id=p_institution_id and driver_id=p_driver_id and status='active') then raise exception 'Driver is not connected';end if;select * into inst from public.institutions where id=p_institution_id;v_area:=p_length*4;v_carpet_total:=round(v_area*p_sale_price,2);
 for addon in select value from jsonb_array_elements(coalesce(p_addons,'[]'::jsonb)) loop v_addon_id:=nullif(addon->>'addon_type_id','')::uuid;if v_addon_id is not null then select * into a from public.addon_types where id=v_addon_id and institution_id=p_institution_id and is_active for update;if not found or a.behavior<>'customer_addon' then raise exception 'Add-on unavailable';end if;v_qty:=case when a.calculation_basis='sale_area' then v_area else coalesce((addon->>'quantity')::numeric,0) end;else v_qty:=coalesce((addon->>'quantity')::numeric,0);end if;v_sale_unit:=coalesce((addon->>'sale_unit_price')::numeric,0);v_cost_unit:=coalesce((addon->>'cost_unit_price')::numeric,0);if v_qty<=0 or v_sale_unit<0 or v_cost_unit<0 then raise exception 'Invalid add-on values';end if;v_addon_sales:=v_addon_sales+round(v_qty*v_sale_unit,2);end loop;
 v_total:=round(v_carpet_total+v_addon_sales,2);if jsonb_typeof(coalesce(p_payments,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_payments,'[]'::jsonb))=0 then raise exception 'At least one payment is required';end if;
 for payment in select value from jsonb_array_elements(p_payments) loop v_method:=coalesce(nullif(trim(payment->>'method'),''),'other');v_amount:=coalesce((payment->>'amount')::numeric,0);if v_amount<=0 then raise exception 'Payment amount must be positive';end if;v_paid:=v_paid+v_amount;if v_primary_method='other' then v_primary_method:=v_method;end if;end loop;if round(v_paid,2)<>round(v_total,2) then raise exception 'Payments must equal sale total';end if;
 v_seller_profit:=round(greatest((p_sale_price-item.wholesale_price)*v_area,0),2);v_commission:=round(v_seller_profit*coalesce(seller.commission_rate,0),2);
 insert into public.sales(institution_id,branch_id,inventory_id,seller_id,driver_id,customer_name,length,width,area,sale_price_per_sqm,wholesale_price_snapshot,supplier_unit_cost_snapshot,installation_amount,glue_gallons,glue_amount,iron_pieces,iron_amount,driver_fee,customer_payment,payment_fee,seller_profit,seller_commission,total,notes,status) values(p_institution_id,item.branch_id,item.id,p_seller_id,p_driver_id,coalesce(trim(p_customer_name),''),p_length,4,v_area,p_sale_price,item.wholesale_price,cost_row.supplier_price,0,0,0,0,0,p_driver_fee,v_primary_method,0,v_seller_profit,v_commission,v_total,coalesce(trim(p_notes),''),'completed') returning id into result_id;
 for addon in select value from jsonb_array_elements(coalesce(p_addons,'[]'::jsonb)) loop v_addon_id:=nullif(addon->>'addon_type_id','')::uuid;v_supplier_id:=nullif(addon->>'supplier_id','')::uuid;if v_addon_id is not null then select * into a from public.addon_types where id=v_addon_id and institution_id=p_institution_id and is_active;v_name:=a.name;v_unit:=a.unit;v_qty:=case when a.calculation_basis='sale_area' then v_area else (addon->>'quantity')::numeric end;else v_name:=trim(coalesce(addon->>'name',''));v_unit:=trim(coalesce(addon->>'unit','piece'));v_qty:=(addon->>'quantity')::numeric;end if;v_sale_unit:=(addon->>'sale_unit_price')::numeric;v_cost_unit:=(addon->>'cost_unit_price')::numeric;insert into public.sale_addons(institution_id,sale_id,addon_type_id,name_snapshot,unit_snapshot,quantity,sale_unit_price,cost_unit_price,supplier_id) values(p_institution_id,result_id,v_addon_id,v_name,v_unit,v_qty,v_sale_unit,v_cost_unit,v_supplier_id);end loop;
 for payment in select value from jsonb_array_elements(p_payments) loop v_method:=coalesce(nullif(trim(payment->>'method'),''),'other');v_amount:=(payment->>'amount')::numeric;v_reference:=coalesce(trim(payment->>'reference'),'');v_rate:=case v_method when 'visa' then inst.visa_fee_rate when 'tabby' then inst.tabby_fee_rate when 'tamara' then inst.tamara_fee_rate else 0 end;insert into public.sale_payments(institution_id,sale_id,method,amount,reference,fee_rate_snapshot,fee_amount,created_by) values(p_institution_id,result_id,v_method,v_amount,v_reference,v_rate,round(v_amount*v_rate,2),auth.uid());v_fee:=v_fee+round(v_amount*v_rate,2);end loop;
 update public.sales set payment_fee=v_fee where id=result_id;update public.inventory_items set remaining_length=remaining_length-p_length,last_sold_at=now() where id=item.id;insert into public.inventory_movements(institution_id,branch_id,inventory_id,movement_type,length_delta,source_type,source_id,note,created_by) values(p_institution_id,item.branch_id,item.id,'sale',-p_length,'sale',result_id,'Sale stock deduction',auth.uid());
 if p_driver_id is not null then insert into public.driver_trips(sale_id,institution_id,branch_id,driver_id,seller_id,amount) values(result_id,p_institution_id,item.branch_id,p_driver_id,p_seller_id,p_driver_fee);end if;return result_id;end$$;
revoke all on function public.record_sale_v2(uuid,uuid,uuid,uuid,text,numeric,numeric,numeric,text,jsonb,jsonb) from public,anon;grant execute on function public.record_sale_v2(uuid,uuid,uuid,uuid,text,numeric,numeric,numeric,text,jsonb,jsonb) to authenticated;
