-- Branch filtered account statements, supplier/driver payments, invoice branch snapshot.
create or replace function public.record_supplier_account_entry(p_institution_id uuid,p_supplier_id uuid,p_entry_type text,p_amount numeric,p_payment_method text default '',p_reference text default '',p_note text default '',p_branch_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$declare rid uuid;effect numeric;begin
 if p_branch_id is null then if not public.has_institution_role(p_institution_id,array['owner','accountant']::public.institution_role[]) then raise exception 'Insufficient permission';end if;elsif not public.can_manage_branch(p_branch_id,'financials') then raise exception 'Insufficient branch permission';end if;
 effect:=case when p_entry_type='return' then -abs(p_amount) when p_entry_type in('payment','settlement') then -abs(p_amount) else p_amount end;
 insert into public.supplier_account_entries(institution_id,branch_id,supplier_id,entry_type,balance_effect,payment_method,reference,note,created_by) values(p_institution_id,p_branch_id,p_supplier_id,p_entry_type,effect,p_payment_method,p_reference,p_note,auth.uid()) returning id into rid;
 if p_entry_type in('payment','settlement') then update public.suppliers set paid_total=paid_total+abs(p_amount) where id=p_supplier_id and institution_id=p_institution_id;end if;return rid;end$$;
revoke all on function public.record_supplier_account_entry(uuid,uuid,text,numeric,text,text,text,uuid) from public,anon;grant execute on function public.record_supplier_account_entry(uuid,uuid,text,numeric,text,text,text,uuid) to authenticated;

create or replace function public.record_driver_account_entry(p_institution_id uuid,p_driver_id uuid,p_entry_type text,p_amount numeric,p_payment_method text default 'cash',p_reference text default '',p_note text default '',p_branch_id uuid default null)
returns uuid language plpgsql security definer set search_path=public as $$declare rid uuid;begin
 if p_branch_id is null then if not public.has_institution_role(p_institution_id,array['owner','accountant']::public.institution_role[]) then raise exception 'Insufficient permission';end if;elsif not public.can_manage_branch(p_branch_id,'financials') then raise exception 'Insufficient branch permission';end if;
 insert into public.driver_account_entries(institution_id,branch_id,driver_id,entry_type,balance_effect,payment_method,reference,note,created_by) values(p_institution_id,p_branch_id,p_driver_id,p_entry_type,-abs(p_amount),p_payment_method,p_reference,p_note,auth.uid()) returning id into rid;return rid;end$$;
revoke all on function public.record_driver_account_entry(uuid,uuid,text,numeric,text,text,text,uuid) from public,anon;grant execute on function public.record_driver_account_entry(uuid,uuid,text,numeric,text,text,text,uuid) to authenticated;

create or replace function public.supplier_account_statement_branch(p_institution_id uuid,p_supplier_id uuid,p_from timestamptz,p_to timestamptz,p_branch_id uuid default null)
returns table(event_time timestamptz,event_type text,reference text,description text,amount numeric,created_by_name text,running_balance numeric)
language plpgsql stable security definer set search_path=public as $$begin
 if not public.has_institution_role(p_institution_id,array['owner','accountant']::public.institution_role[]) then raise exception 'Insufficient permission';end if;
 return query with x as(select e.*,coalesce(p.full_name,'') creator from public.supplier_account_entries e left join public.profiles p on p.id=e.created_by where e.institution_id=p_institution_id and e.supplier_id=p_supplier_id and e.created_at>=p_from and e.created_at<p_to and (p_branch_id is null or e.branch_id=p_branch_id))
 select x.created_at,x.entry_type,x.reference,x.note,x.balance_effect,x.creator,sum(x.balance_effect) over(order by x.created_at,x.id) from x order by x.created_at desc;end$$;
revoke all on function public.supplier_account_statement_branch(uuid,uuid,timestamptz,timestamptz,uuid) from public,anon;grant execute on function public.supplier_account_statement_branch(uuid,uuid,timestamptz,timestamptz,uuid) to authenticated;

create or replace function public.issue_tax_invoice(p_sale_id uuid,p_customer_name text default '',p_customer_cr text default '',p_customer_tax text default '',p_customer_address text default '',p_invoice_kind text default 'simplified',p_discount numeric default 0)
returns uuid language plpgsql security definer set search_path=public as $$declare s public.sales%rowtype;i public.institutions%rowtype;rid uuid;num bigint;carpet numeric;addons numeric;sub numeric;taxable numeric;vat numeric;totalvat numeric;begin
 select * into s from public.sales where id=p_sale_id;if not found then raise exception 'Sale not found';end if;if not((s.seller_id=auth.uid()) or (public.can_access_branch(s.branch_id) and public.has_institution_role(s.institution_id,array['owner','accountant']::public.institution_role[]))) then raise exception 'Insufficient permission';end if;
 if exists(select 1 from public.invoices where sale_id=s.id) then select id into rid from public.invoices where sale_id=s.id;return rid;end if;
 select * into i from public.institutions where id=s.institution_id;carpet:=round(s.area*s.sale_price_per_sqm,2);select coalesce(sum(quantity*sale_unit_price),0) into addons from public.sale_addons where sale_id=s.id;sub:=carpet+addons;taxable:=greatest(sub-coalesce(p_discount,0),0);vat:=round(taxable*.15,2);totalvat:=taxable+vat;
 insert into public.invoice_counters(institution_id,next_number) values(s.institution_id,2) on conflict(institution_id) do update set next_number=public.invoice_counters.next_number+1 returning next_number-1 into num;
 insert into public.invoices(institution_id,branch_id,sale_id,invoice_number,seller_id,customer_name,customer_commercial_registration,customer_tax_number,item_name,color,length,width,area,price_per_sqm,carpet_amount,installation_amount,glue_gallons,glue_amount,iron_pieces,iron_amount,driver_fee,payment_method,subtotal,vat_rate,vat_amount,total_with_vat,created_by,invoice_kind,customer_address,seller_name,discount_amount,taxable_amount,payment_summary,addons_summary,addons_amount)
 select s.institution_id,s.branch_id,s.id,num,s.seller_id,coalesce(p_customer_name,s.customer_name),coalesce(p_customer_cr,''),coalesce(p_customer_tax,''),iv.name,iv.color,s.length,s.width,s.area,s.sale_price_per_sqm,carpet,0,0,0,0,0,s.driver_fee,s.customer_payment::text,sub,.15,vat,totalvat,auth.uid(),p_invoice_kind,coalesce(p_customer_address,''),coalesce(pr.full_name,''),coalesce(p_discount,0),taxable,(select string_agg(method||': '||amount,' / ') from public.sale_payments where sale_id=s.id),(select string_agg(name_snapshot||' × '||quantity,' / ') from public.sale_addons where sale_id=s.id),addons from public.inventory_items iv left join public.profiles pr on pr.id=s.seller_id where iv.id=s.inventory_id returning id into rid;return rid;end$$;
revoke all on function public.issue_tax_invoice(uuid,text,text,text,text,text,numeric) from public,anon;grant execute on function public.issue_tax_invoice(uuid,text,text,text,text,text,numeric) to authenticated;
