-- Stage 2: immutable ZATCA XML metadata and party/address snapshots. Financial snapshot is untouched.
alter table public.institutions add column if not exists zatca_street_name text,add column if not exists zatca_building_number text,add column if not exists zatca_district text,add column if not exists zatca_city text,add column if not exists zatca_postal_code text,add column if not exists zatca_country_code text default 'SA';
alter table public.branches add column if not exists zatca_street_name text,add column if not exists zatca_building_number text,add column if not exists zatca_district text,add column if not exists zatca_city text,add column if not exists zatca_postal_code text,add column if not exists zatca_country_code text;
alter table public.invoices add column if not exists zatca_uuid uuid,add column if not exists seller_legal_name_snapshot text,add column if not exists seller_vat_number_snapshot text,add column if not exists seller_id_scheme_snapshot text,add column if not exists seller_id_value_snapshot text,add column if not exists seller_street_snapshot text,add column if not exists seller_building_number_snapshot text,add column if not exists seller_district_snapshot text,add column if not exists seller_city_snapshot text,add column if not exists seller_postal_code_snapshot text,add column if not exists seller_country_code_snapshot text,add column if not exists buyer_id_scheme_snapshot text,add column if not exists buyer_id_value_snapshot text,add column if not exists buyer_street_snapshot text,add column if not exists buyer_building_number_snapshot text,add column if not exists buyer_district_snapshot text,add column if not exists buyer_city_snapshot text,add column if not exists buyer_postal_code_snapshot text,add column if not exists buyer_country_code_snapshot text,add column if not exists xml_content text,add column if not exists xml_standard_version text,add column if not exists xml_generator_version text,add column if not exists xml_generated_at timestamptz;
create or replace function public.capture_invoice_zatca_snapshot() returns trigger language plpgsql security definer set search_path=public as $$
declare inst public.institutions%rowtype;br public.branches%rowtype;begin
select * into inst from public.institutions where id=new.institution_id;select * into br from public.branches where id=new.branch_id and institution_id=new.institution_id;
new.zatca_uuid:=coalesce(new.zatca_uuid,gen_random_uuid());new.seller_legal_name_snapshot:=inst.name;new.seller_vat_number_snapshot:=inst.tax_number;new.seller_id_scheme_snapshot:=case when nullif(trim(inst.commercial_registration),'') is null then null else 'CRN' end;new.seller_id_value_snapshot:=nullif(trim(inst.commercial_registration),'');
new.seller_street_snapshot:=coalesce(nullif(trim(br.zatca_street_name),''),nullif(trim(inst.zatca_street_name),''));new.seller_building_number_snapshot:=coalesce(nullif(trim(br.zatca_building_number),''),nullif(trim(inst.zatca_building_number),''));new.seller_district_snapshot:=coalesce(nullif(trim(br.zatca_district),''),nullif(trim(inst.zatca_district),''));new.seller_city_snapshot:=coalesce(nullif(trim(br.zatca_city),''),nullif(trim(inst.zatca_city),''));new.seller_postal_code_snapshot:=coalesce(nullif(trim(br.zatca_postal_code),''),nullif(trim(inst.zatca_postal_code),''));new.seller_country_code_snapshot:=coalesce(nullif(trim(br.zatca_country_code),''),nullif(trim(inst.zatca_country_code),''),'SA');
new.buyer_id_scheme_snapshot:=case when nullif(trim(new.customer_commercial_registration),'') is null then null else 'CRN' end;new.buyer_id_value_snapshot:=nullif(trim(new.customer_commercial_registration),'');return new;end$$;
revoke all on function public.capture_invoice_zatca_snapshot() from public,anon,authenticated;
drop trigger if exists capture_invoice_zatca_snapshot on public.invoices;create trigger capture_invoice_zatca_snapshot before insert on public.invoices for each row execute function public.capture_invoice_zatca_snapshot();
create unique index if not exists invoices_zatca_uuid_uidx on public.invoices(zatca_uuid) where zatca_uuid is not null;
create or replace function public.prevent_invoice_zatca_snapshot_mutation() returns trigger language plpgsql set search_path=public as $$
begin
if old.zatca_uuid is distinct from new.zatca_uuid or old.seller_legal_name_snapshot is distinct from new.seller_legal_name_snapshot or old.seller_vat_number_snapshot is distinct from new.seller_vat_number_snapshot or old.seller_id_scheme_snapshot is distinct from new.seller_id_scheme_snapshot or old.seller_id_value_snapshot is distinct from new.seller_id_value_snapshot or old.seller_street_snapshot is distinct from new.seller_street_snapshot or old.seller_building_number_snapshot is distinct from new.seller_building_number_snapshot or old.seller_district_snapshot is distinct from new.seller_district_snapshot or old.seller_city_snapshot is distinct from new.seller_city_snapshot or old.seller_postal_code_snapshot is distinct from new.seller_postal_code_snapshot or old.seller_country_code_snapshot is distinct from new.seller_country_code_snapshot or old.buyer_id_scheme_snapshot is distinct from new.buyer_id_scheme_snapshot or old.buyer_id_value_snapshot is distinct from new.buyer_id_value_snapshot or old.buyer_street_snapshot is distinct from new.buyer_street_snapshot or old.buyer_building_number_snapshot is distinct from new.buyer_building_number_snapshot or old.buyer_district_snapshot is distinct from new.buyer_district_snapshot or old.buyer_city_snapshot is distinct from new.buyer_city_snapshot or old.buyer_postal_code_snapshot is distinct from new.buyer_postal_code_snapshot or old.buyer_country_code_snapshot is distinct from new.buyer_country_code_snapshot then raise exception 'ZATCA invoice party snapshot is immutable';end if;
if old.xml_content is not null and(old.xml_content is distinct from new.xml_content or old.xml_standard_version is distinct from new.xml_standard_version or old.xml_generator_version is distinct from new.xml_generator_version or old.xml_generated_at is distinct from new.xml_generated_at)then raise exception 'Generated invoice XML is immutable';end if;return new;end$$;
revoke all on function public.prevent_invoice_zatca_snapshot_mutation() from public,anon,authenticated;
drop trigger if exists invoices_zatca_immutable on public.invoices;create trigger invoices_zatca_immutable before update on public.invoices for each row execute function public.prevent_invoice_zatca_snapshot_mutation();

